kafka:
  bootstrap-server: "127.0.0.1:9092"
  topic:
    order: order
    payment: payment

product:
  host: "https://dummyjson.com"
  url:
    inquiry: "/products/search?q="

spring:
  main:
    allow-bean-definition-overriding: true